spring.application.name=spendlens

spring.datasource.url=jdbc:mysql://localhost:3306/spendlens
spring.datasource.username=root
spring.datasource.password=181104

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

openai.api.key=${OPENAI_API_KEY}